visualization_task:
  description: >
    Understand the user query regarding the stock, then plan thoroughly about what visualizations will be needed to answer this {user_question}.
    Based on the user query, you will need to WRITE the code which fetches the data from yahoo finance and then handles the data to generate visualizations that will answer the user query and then EXECUTE THE CODE.
    IMPORTANT: The choice of plots should be MATHEMATICALLY RELEVANT and all the calculations should be ACCURATE.
    If the query needs to take into account the present time, then the present time is {present_time}.
  expected_output: >
    The plots of matplotlib to be saved as images in the \assets\images folder.
  agent: visualizer_Agent