visualization_task:
  description: >
    Understand the user query regarding the stock, then plan thoroughly about what visualizations will be needed to answer this {user_question}.
    Based on the user query, you will need to write the code which fetches the data from yahoo finance and then handles the data to generate visualizations that will answer the user query.
    IMPORTANT: The choice of plots should be MATHEMATICALLY RELEVANT and all the calculations should be ACCURATE.
    If the query needs to take into account the present time, then the present time is {present_time}.
  expected_output: >
    The plots of matplotlib to be saved as images in the current directory.
  agent: visualizer_Agent







# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
